### PR TITLE
add files

### PR DESCRIPTION
**Pull request by lsimmons1832**

### CODE REVIEW

**Comment by zoeames** [comment]
@lsimmons1832 is this ready to be looked at or are you still working?

**Comment by lsimmons1832** [comment]
@zoeames no I'm still working on this

**Comment by lsimmons1832** [comment]
@zoeames you can look at this now, but I still need to fix the application so that it detects the key press for enter

**Comment by zoeames** [comment]
i will wait until you are completely done

**Comment by zoeames** [comment]
very nice quiz.  One minor issue.  When I don't type in one of the inputs it pulls up an array - this is correct.  However it still tries to run the tree building function.  Can you edit your verifyInput function to only run the buildTree function if both inputs are valid?

**Comment by morecallan** [comment]
👍 all good!

**Pull request merged**
